df <- read.table("C:/Users/cramer/Desktop/Coursera/Assignment1/household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?", stringsAsFactors=FALSE)
dfsubset <- rbind(subset(df, df$Date == "1/2/2007"), subset(df, df$Date == "2/2/2007"))
DateTime <- paste(dfsubset$Date, dfsubset$Time, sep = " ")
workingdata <- cbind(DateTime, dfsubset[,3:9])
workingdata$DateTime <- strptime(workingdata$DateTime, format="%d/%m/%Y %H:%M:%S")
png(file = "plot1.png", width = 480, height = 480)
par(mfrow = c(1, 1),  mar = c(5.1, 4.1, 4.1, 2.1))
hist(workingdata$Global_active_power, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", ylab = "Frequency", col="red")
dev.off()
